<template>
  <div class="container">
    <h1>Speedy Review</h1>

    <p class="intro">
      Speedy Review is a powerful tool designed to enhance your git workflow by
      automatically generating meaningful commit messages based on code changes.
      It aims to save developers time and improve the quality of commit logs,
      making code reviews faster and change logs more useful.
    </p>

    <section>
      <h2>Why Use Speedy Review?</h2>
      <ol>
        <li>
          <strong>Save Time</strong>: Automate commit message creation, allowing
          developers to focus on coding.
        </li>
        <li>
          <strong>Improve Code Review Efficiency</strong>: Clear, descriptive
          commit messages facilitate faster review processes.
        </li>
        <li>
          <strong>Enhance Change Logs</strong>: Generate more informative and useful
          project history tracking.
        </li>
        <li>
          <strong>Ensure Consistency</strong>: Maintain a consistent style and quality
          of commit messages across your team or project.
        </li>
        <li>
          <strong>Promote Best Practices</strong>: Learn to write more informative
          commits by analyzing suggested messages.
        </li>
      </ol>
    </section>

    <section>
      <h2>Features</h2>
      <ul>
        <li>
          <strong>Git Hook Integration</strong>: Automatically suggest commit
          messages during the commit process.
        </li>
        <li>
          <strong>Standalone Script (victor.py)</strong>: Analyze and update
          commit messages for specific commits.
        </li>
        <li>
          <strong>Microservice Architecture</strong>: Utilize a microservice for
          diff analysis and message generation (optional).
        </li>
        <li>
          <strong>Customizable Message Templates</strong>: Define commit message
          templates to align with your team's conventions.
        </li>
        <li>
          <strong>Multi-language Support</strong>: Generate appropriate commit messages
          for various programming languages and file types.
        </li>
        <li>
          <strong>Historical Analysis</strong>: Analyze past commits to suggest
          improvements and maintain consistency with previous high-quality messages.
        </li>
        <li>
          <strong>Commit Categorization</strong>: Automatically categorize
          commits (e.g., feat, fix, docs, style) based on changes made.
        </li>
        <li>
          <strong>Interactive Mode</strong>: Refine suggested commit messages
          through a command-line interface.
        </li>
      </ul>
    </section>

    <section>
      <h2>Setup for Use</h2>
      <ol>
        <li>Install dependencies: Python and Git</li>
        <li>Add Git hook to your project</li>
        <li>
          Set environment variables:
          <ul>
            <li><code>SPEEDYREVIEW_API_KEY</code>: API string for authentication</li>
            <li><code>SPEEDYREVIEW_ENDPOINT_URL</code>: URL of the microservice</li>
          </ul>
        </li>
        <li>
          Commit as usual. The initial message will be generated by Speedy Review.
          You can accept it entirely, partially, or create your own.
        </li>
      </ol>
    </section>

    <section>
      <h2>Typical Workflow</h2>
      <ol>
        <li>Initiate a <code>git commit</code></li>
        <li>Your editor will open with a generated commit message</li>
        <li>Edit the commit message as desired</li>
        <li>Save and exit your editor</li>
        <li>Your commit is now complete with an informative message</li>
      </ol>
    </section>

    <section>
      <h2>Victor.py Script</h2>
      <p>
        Use <code>victor.py</code> to analyze and update historical commit messages:
      </p>
      <pre><code>python victor.py &lt;commit_hash&gt;</code></pre>
      <p>This script will:</p>
      <ol>
        <li>Checkout the specified commit</li>
        <li>Analyze changes and existing commit message</li>
        <li>Suggest a new commit message and initiate a <code>git commit --amend</code></li>
        <li>Update the commit message if approved, creating a new branch</li>
      </ol>
    </section>

    <section>
      <h2>Contributing</h2>
      <p>
        We welcome contributions! Please fork the repository and submit a pull
        request at the
        <a href="https://github.com/tompscanlan/speedy-review"
        @click="posthogClick"
          >GitHub repository</a
        >.
      </p>
    </section>

    <section>
      <h2>License</h2>
      <p>This project is licensed under the Apache 2.0 License.</p>
    </section>

    <section>
      <h2>About</h2>
      <p>
        For more information, visit the
        <a href="https://github.com/tompscanlan/speedy-review"
        @click="posthogClick"
          >GitHub repository</a
        >.
      </p>
    </section>
  </div>
</template>

<script setup>
import { useNuxtApp } from '#app';
const { $posthog } = useNuxtApp();

function posthogClick(event) {
  event.preventDefault(); // Prevent default anchor behavior
  $posthog.capture('Click', {
    dest: 'github.com',
    src: 'https://speedy-review.butterhead.net/index.vue'
  });
  window.location.href = event.target.href; // Navigate to the link after capturing
}
</script>

<style scoped>
.container {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
  font-family: Arial, sans-serif;
  line-height: 1.6;
  color: #333;
}

h1 {
  font-size: 2.5rem;
  color: #2c3e50;
  margin-bottom: 1rem;
}

h2 {
  font-size: 1.8rem;
  color: #3498db;
  margin-top: 2rem;
  margin-bottom: 1rem;
}

h3 {
  font-size: 1.2rem;
  color: #2980b9;
  margin-top: 1.5rem;
  margin-bottom: 0.5rem;
}
h4 {
  font-size: .8rem;
  color: #2980b9;
  margin-top: 1.5rem;
  margin-bottom: 0.5rem;
}
p {
  margin-bottom: 1rem;
}

.intro {
  font-size: 1.1rem;
  color: #34495e;
  border-left: 4px solid #3498db;
  padding-left: 1rem;
  margin-bottom: 2rem;
}

ul,
ol {
  margin-bottom: 1rem;
  padding-left: 2rem;
}

li {
  margin-bottom: 0.5rem;
}

code {
  background-color: #f8f8f8;
  padding: 0.2rem 0.4rem;
  border-radius: 3px;
  font-family: monospace;
}

pre {
  background-color: #f8f8f8;
  padding: 1rem;
  border-radius: 5px;
  overflow-x: auto;
}

section {
  margin-bottom: 2rem;
}
</style>
